admissionController:
  replicas: 2
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
backgroundController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
cleanupController:
  replicas: 1
reportsController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
